# Generated by Django 4.0.5 on 2022-06-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='created_by',
        ),
    ]
