# Generated by Django 4.0.5 on 2022-06-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_rename_fast_name_user_f_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='student', max_length=60),
        ),
    ]
