# Generated by Django 4.0.5 on 2022-06-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_alter_user_img_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
