# Generated by Django 4.1.4 on 2022-12-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='common_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Common',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
